# -------------------
# Theme Config
# --------------------
title: LuminousArizona
category_dir: category
photographer: Jason Robert O'Kennedy

colors:
  #light-mode colors
  primary_bg: "#0d042b"
  primary_bg_2: "#0d042b"
  primary_bg_3: "#0d042b"
  primary_text: "#fdfcf9"
  base_bg: "#fdfcf9"
  base_bg_2: "#eaeaea"
  base_bg_3: "#faebd7"
  base_text: "#0d042b"
  base_text_2: "#3b364c"
  logo_text: "#0d042b"
  header_text: "#0d042b"

  # dark-mode colors
  primary_bg_dark: "#fdfcf9"
  primary_bg_2_dark: "#fdfcf9"
  primary_bg_3_dark: "#fdfcf9"
  primary_text_dark: "#212529"
  base_bg_dark: "#212529"
  base_bg_2_dark: "#191c1e"
  base_bg_3_dark: "#251654"
  base_text_dark: "#f5f5ec"
  base_text_2_dark: "#929eaf"
  logo_text_dark: "#fdfcf9"
  header_text_dark: "#fdfcf9"

fonts:
  use_google_fonts: true
  google_fonts_url: https://fonts.googleapis.com/css2?family=Cinzel+Decorative:wght@400;700;900&family=Quicksand:wght@30
  use_self_hosted_fonts: false # font files must be placed in /assets/fonts folder and the @font-face definitions must be added to /assets/css/fonts.css
  heading: "'Cinzel Decorative'"
  base: "'Quicksand'"
  monospace: "'Quicksand'"
  logo: "'Cinzel Decorative'"
  
logo:
  logo_text: LuminousArizona
  logo_image: ""
  logo_image_mobile: ""
  logo_image_invert: ""
  logo_image_invert_mobile: ""
  logo_image_desktop_height: 28px
  logo_image_desktop_width: 28px
  logo_image_mobile_height: 28px
  logo_image_mobile_width: 28px
  show_logo_image_on_mobile: false
  show_logo_image_on_desktop: false
  show_logo_text_on_mobile: true
  show_logo_text_on_desktop: true

header:
  fixed: false

open_graph:
  meta_opengraph_type: website
  meta_twitter_card: summary
  meta_twitter_site: "@"
  meta_twitter_creator: "@"

darkmode:
  enable_dark_mode: true
  show_dark_mode_toggle_in_header: true
  show_dark_mode_toggle_in_footer: false
  show_dark_mode_toggle_in_bottom: false
  show_dark_mode_toggle_in_mobile_menu: true

cookie_banner:
  enabled: true
  show_manage_cookies_at_bottom: true

analytics:
  google_analytics_id: "" # G-XXXXXXXXXX
  gtm_id: "" # GTM-XXXXXXXX
  plausible_data_domain: "" # LuminousArizona.com
  plausible_src: ""
  umami_data_website_id: "" # ddd14336-5fb0-4cdd-8f32-e1bfa906cc2b
  umami_src: "" # https://analytics.eu.umami.is/script.js

comments:
  commento:
    enabled: false # you must have a commento account and be on the correct domain. does not work locally.
  disqus:
    shortname:  # Your disqus shortcode for example "zerostatic". leave this blank ie "" to disable.

newsletter:
  mailchimp:
    form_action_url: 
    form_title: Let's keep in touch

contact_form:
  use_netlify_form: true
  use_formspree_form: false
  formspree_endpoint: ""
  netlify_form_name: "contact"

menu:
  show_dropdown_items_in_mobile_menu: false
  show_social_media_in_mobile_menu: true

footer:
  enable_footer: true # show/hide the entire footer
  footer_title: &#168;2025 LuminousArizona | Jason Robert O'Kennedy<br>| ALL RIGHTS RESERVED
  footer_description: Essays of Arizona's places and things that makes it unique.
  enable_social_media_icons: true
  enable_contact_details: false
  enable_menu_footer_primary: true
  enable_menu_footer_secondary: true
  enable_menu_footer_tertiary: false
  footer_primary_menu_title: Popular Projects
  footer_secondary_menu_title: LuminousArizona
  footer_tertiary_menu_title: Other

bottom:
  enable_bottom: false # show/hide the entire bottom (below the footer)
  enable_bottom_menu: false # if enabled, the bottom menu can be edited in `_data/menu.yml`
  copyright_text: "© 2025 LuminousArizona"
  show_rss_icon: false
